[versions]
kotlin = "1.9.0"
jvm = "17"
mockk = "1.13.5"

[libraries]
mockk = { module = "io.mockk:mockk", version.ref = "mockk"}

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }